services:
  _defaults:
    autowire: true

  App\Games\Duizenden\Actions\Deal\Deal:
    bind:
      $state_machine: "@state_machine.duizenden"

  App\Games\Duizenden\Actions\DrawCard\FromUndrawnPool:
    arguments: [ "@state_machine.duizenden" ]

  App\Games\Duizenden\Actions\DrawCard\FromDiscardedPool:
    arguments: [ "@state_machine.duizenden" ]

  App\Games\Duizenden\Actions\Meld\MeldCards:
    arguments: [ "@state_machine.duizenden" ]

  App\Games\Duizenden\Actions\Meld\ExtendMeld:
    arguments: [ "@state_machine.duizenden" ]

  App\Games\Duizenden\Actions\DiscardCard\DiscardCard:
    bind:
      $state_machine: "@state_machine.duizenden"

  App\Games\Duizenden\Actions\Hand\ReorderCard: ~

  App\Games\Duizenden\Actions\Meld\RevertMeld: ~
