services:
  app.deck.locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: ['container.service_locator']
    arguments:
      -

      standard108_blue: '@App\Decks\Standard108\DeckBlue'
      standard108_red: '@App\Decks\Standard108\DeckRed'

  App\Deck\DeckFactory:
      arguments: [ '@app.deck.locator' ]

  App\Decks\Standard108\DeckBlue:
    shared: false

  App\Decks\Standard108\DeckRed:
    shared: false
