services:
  app.game.locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: ['container.service_locator']
    arguments:
      -

      duizenden: '@App\Games\Duizenden\Game'

  App\Game\GameFactory:
      arguments: [ '@app.game.locator' ]

  App\Games\Duizenden\Initializer\Initializer: ~

  App\Games\Duizenden\Game:
    shared: false
    arguments:
      - '@App\Games\Duizenden\Initializer\Initializer'
      - '@App\Games\Duizenden\Score\ScoreCalculator'
      - '@state_machine.duizenden'

