services:
  app.game.locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: ['container.service_locator']
    arguments:
      -

      duizenden: '@App\Games\Duizenden\Game'

  App\Game\GameFactory:
      arguments: [ '@app.game.locator' ]

  App\Games\Duizenden\Initializer\Initializer: ~

  App\Games\Duizenden\Game:
    shared: false
    arguments:
      - '@App\Games\Duizenden\Initializer\Initializer'
      - '@App\Games\Duizenden\Score\ScoreCalculator'
      - '@state_machine.duizenden'
      - '@App\Games\Duizenden\Dealer\DealerFinder'
      - '@App\Games\Duizenden\Actions\Deal\Deal'
      - '@App\Games\Duizenden\Actions\DrawCard\FromDiscardedPool'
      - '@App\Games\Duizenden\Actions\DrawCard\FromUndrawnPool'
      - '@App\Games\Duizenden\Actions\Meld\MeldCards'
      - '@App\Games\Duizenden\Actions\Meld\ExtendMeld'
      - '@App\Games\Duizenden\Actions\RecreateUndrawnPool\RecreateUndrawnPool'
      - '@App\Games\Duizenden\Actions\DiscardCard\DiscardCard'
      - '@App\Games\Duizenden\Actions\Hand\ReorderCard'
      - '@App\Games\Duizenden\Actions\Meld\RevertMeld'

