doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/model/App/Entity'
                prefix: 'App\Entity'
                alias: App

            App\Chat:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/config/model/App/Chat/Entity'
              prefix: 'App\Chat\Entity'
              alias: App\Chat

            App\Games\Duizenden:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/model/App/Games/Duizenden/Entity'
                prefix: 'App\Games\Duizenden\Entity'
                alias: App\Games\Duizenden

            App\Lobby:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/model/App/Lobby/Entity'
                prefix: 'App\Lobby\Entity'
                alias: App\Lobby\Entity
