parameters:
  authentication.user.check_path: '/authenticate-user'

security:
  providers:
    chain_provider:
        chain:
            providers: [user_provider, anonymous_player_provider]

    user_provider:
      id: App\Security\UserProvider\UserProvider

    anonymous_player_provider:
      id: App\Security\UserProvider\AnonymousPlayerProvider

  encoders:
    App\Entity\User:
      algorithm: auto

  firewalls:
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
    main:
      pattern: ^/
      anonymous: true
      anonymous_player:
        identification_path: /login
        validation_path: /authenticate-anonymous
        success_path: /lobby
        identification_form_type: App\Form\Authentication\AnonymousLoginType
        identification_form_field: name
      provider: chain_provider
      form_login:
        login_path: /login
        username_parameter: authenticate_user[username]
        password_parameter: authenticate_user[password]
        check_path: '%authentication.user.check_path%'
        default_target_path: /lobby
        always_use_default_target_path: true
      logout:
        path: /logout
        target: /lobby

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
