authentication.login:
  path: /login
  methods: ['GET']
  controller: App\Controller\AuthenticationController::login

authentication.authenticate.anonymous: # Handled by App\Security\FirewallAnonymousPlayerListener
  path: /authenticate-anonymous

authentication.authenticate.user:
  path: /authenticate-user

authentication.logout:
  path: /logout
