game.saved:
  path: /saved
  controller: App\Controller\Main::saved

game.load:
  path: /load/{game_name}/{uuid}
  controller: App\Controller\Main::load
  requirements:
    uuid: '^[0-9a-f]{8}-[0-9a-f]{4}-[5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
