imports:
    - { resource: services/ }

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
          $state_machine: '@state_machine.duizenden'

    App\:
        resource: '../src/*'
        exclude:
          - '../src/{DependencyInjection,Entity,Repository,Migrations,Tests,Kernel.php}'
          - '../src/Deck/DeckFactory.php'
          - '../src/Shuffler/ShufflerFactory.php'
          - '../src/Shufflers/Overhand/OverhandShuffle.php' # Must ignore this else this service will NOT be shared
          - '../src/DeckRebuilder/DeckRebuilderFactory.php'
          - '../src/DeckRebuilders/DistinctDeckRebuilder.php'
          - '../src/Game/GameFactory.php'
          - '../src/Game/Meta/GameMetaLoader.php'
          - '../src/Games/Duizenden/Game.php'
          - '../src/Games/Duizenden/Actions/*'
          - '../src/Games/Duizenden/MetaLoader.php'
          - '../src/Mercure/SubscriberIdGenerator.php'
          - '../src/Games/Duizenden/GraphQL/Resolver/MyResolverMap.php'
          - '../src/AI/Minimax/State/PossibleStateFactory.php'
          - '../src/Games/Duizenden/AI/ActionGenerator/SequenceCalculator/*'
          - '../src/Games/Duizenden/AI/ContextCloner.php'
          - '../src/AI/Minimax/Context/ContextCloner.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
